version: '3'
services:

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1258
      MYSQL_DATABASE: carsysproj
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD


  carsysproj:
    build: .
    restart: always
    container_name: carsysproj
    ports:
      - "9500:9500"
    depends_on:
      mysql:
        condition: service_healthy